import { useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';
import { 
  Printer as PrinterIcon, 
  Users as UsersIcon, 
  CreditCard as CreditCardIcon, 
  Loader2 as Loader2Icon,
  Filter as FilterIcon
} from 'lucide-react';

interface Student {
  id: string;
  prefix: string;
  first_name: string;
  last_name: string;
  class_level: string;
  room: string;
  academic_year: string;
  parent_phone?: string;
}

// ฝังฟอนต์ Base64 เพื่อให้หน้าต่างพิมพ์แสดงผลถูกต้อง 100% ใน Electron
const FONT_BASE64 = 'AAEAAAAWAQAABABgR0RFRgwJByQAASlEAAAAUkdQT1OM1rlcAAEpmAAAF0ZHU1VC+npHzgABQOAAABqmT1MvMqQuVIcAAAHoAAAAYFBDTFRiW0bNAAEpDAAAADZWRE1YaIVv6gAACjwAAAXgY21hcKcuOncAABAcAAAGhmN2dCAAFAAAAAAYHAAAAAJmZWF0AAYEVwABW4gAAAAsZnBnbQZZnDcAABakAAABc2dhc3AAFwAJAAEo/AAAABBnbHlmefHFYgAAGCAAALwMaGVhZOOWcZ0AAAFsAAAANmhoZWEFewQbAAABpAAAACRobXR4m98CUAAAAkgAAAf0a2Vybr7ZwqwAANgoAAAhPGxvY2F6zamAAADULAAAA/xtYXhwBDoEPwAAAcgAAAAgbW9yeAPXuA0AAVu0AAAmGG5hbWUshnerAAD5ZAAAIpdwb3N04ewapwABG/wAAAz/cHJlcLgAACsAABgYAAAABAABAAAAAQAA2bj+0F8PPPUACQPoAAAAAME4hTwAAAAAwTip3P5V/lsDswNEAAAACQACAAAAAAAAAAEAAANS/wYAHgO6/lX/XQOzAAEAAAAAAAAAAAAAAAAAAAH9AAEAAAH9AdIAKQBWAAYAAQAAAAAACgAAAgACFQADAAEAAwF2AZAABQAAArwCigAAAIwCvAKKAAAB3QAeAPoIBQILBQAEAgACAAOhAABvUAAgWgAAAAAAAAAAcHNrIABAACD7AgNS/wYAPANSAPpgAQGDgAAAAAFUAdwAAAAgAA0CtAAyANgAAACTACYA0AAlAZMAGwFpADQCSQAiAacAEwB4ACUAvgAUAL4AFAEdABIBmwAmAKIAHgDYABQAogAuAQ7/7gFqAB8BagBLAWoAGgFqACIBagAgAWoAGAFqACYBagAhAWoAIQFqACYAogAuAKIAHgGbACwBmwA3AZsALAEbAB8CGAAXAZAAAAF6ADYBlgAXAa8ANgFfADYBXwA2AakAFwG5ADYAkwA2AQj//wF4ADYBYQA2AiQAKAG5ADYB5gAWAXoANgHnABYBewA2AWAAGwF7//sB0gA2AYYAAAJMAAABogARAW4AAAGoABYAxAA0AQb/9wDEAAsBnAArAWAAAADMADsBWAAaAZEAMQFLABsBkQAcAXYAGwDOAAUBNwAkAYYANACPACcAm//WATwANADIADQCWQAtAYYALQGOABwBkQAxAZEAMQDZACoBGgAdAO4ABgGGADQBVQADAfsAAwE+AAABUQADAUEADwDQAA0AmQA8ANAAHAGgABoBPP7RAAAAAADYAAAAAP7fAJcAJgGbACABmwA5AZsAFgGbACIAmQA8AXYANwDUAA4CGAAZAPYAGAEqAAsBpAAXAhgAGQFgAAAA1AAUAZsAJgD+ABkA/gAjANQANgGWADkBdgAtAKIALgDUACMA/gA7AR0AFAEmABMCGAAeAhgAHgIYACMBIQAiAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAkb/+QGWABcBXwA2AV8ANgFfADYBXwA2AJMAHQCTAB0Ak//9AJP/8wGvAAUBuQA2AeYAFgHmABYB5gAWAeYAFgHmABYBmwAvAeYAFgHSADYB0gA2AdIANgHSADYBbgAAAXwAPAGIACkBWAAaAVgAGgFYABoBWAAaAVgAGgFYABoCYAAaAUsAGwF2ABsBdgAbAXYAGwF2ABsAjwAbAI8AGwCP//sAj//xAWoAJgGGAC0BjgAcAY4AHAGOABwBjgAcAY4AHAGbACYBjgAcAYYANAGGADQBhgA0AYYANAFRAAMBsAA9AVEAAwCPADQBaQASANEAEgLHABYCpwAcAWAAGwEaAB0BfgAHAagAFgFBAA8Bjv/vANQAFwDUABcBLgA8AS4AdQEuAE0BLgBQANQAFwEXACoAAAAAAYIAJAF6AA8BfgAPAYkAIQGJACEBmAAPASYAEAFvABgBeQAaAXwADwGAAA8CBwAeAgcAHgGpABgBqQAYAVf/8gHNAA8CFAAgAh8AHgGHACABhwAgAXoAGgGuABEBTwAUAaQAEQGsABEBrAARAX0AKAF9ACgBvwARAb8AEQGpABgBkAARAXcAKgFCABkBegAaAX0AFQGpABgBTwAKAYkAIQG2ABEBfQAVAasAEQHGABEBgwAaAXQAJQGHADYBZQAfAAD/FQE8ABgBPP9eAAD+pwAA/qcAAP6nAAD+pwAA/14AAP71AAD/mwGbAEsAywA1AXkANQDt/9kA8v/WAPT/3QDN/6kBjwA6AAD+3AAA/6cAAP9GAAD+1AAA/3MAAP9OAAD/XgAA/zoBwgA4AcEAJgHBACQBwQAQAcEAIgHBAB0BwQAdAcEAEgHBABgBwQAgAcEAGgIKADYCuQBNAAD/8gAA/80AAP/yAAD/XgFoABUC0AAWAPcASQD3AEkA9wBJAXIATgFyAE4BcgBOAXYAJwF2ACcA2AAYAd8ALgM9ACIAfQAPANYADwC3AAsAtwATAKL/3AGWAAAA0QAWAfkADgHFACMBOQAfAT0AHAHaAAABvgA2AZsAGQGbADcBXgAXAmoANQDy/9kBmwAtAZsANwGbADkBmwA5AYIAIQGQABEBUAAaAAD+VQAA/lUAAP5VAAD+VQAA/zkAAP7XAAD+rwAA/uUAAP8AAAD/owAA/xYAAP7hAAD/awAA/0UCAAAeAAD+qgAA/tEAAP6NAAD/VQAA/t0AAP6iAAD/IQAA/xcAAP9eAAD+9QAA/5sBqQAYAcYAEQFbAAoBlAAKA7oAOgGQAAABWAAaAZAAAAFYABoBkAAAAVgAGgGQAAABWAAaAZAAAAFYABoBkAAAAVgAGgGQAAABWAAaAZAAAAFYABoBkAAAAVgAGgGQAAABWAAaAZAAAAFYABoBkAAAAVgAGgGQAAABWAAaAZAAAAFYABoBkAAAAVgAGgFfADYBdgAbAV8ANgF2ABsBXwA2AXYAGwFfADYBdgAbAV8ANgF2ABsBXwA2AXYAGwFfADYBdgAbAV8ANgF2ABsAkwAQAI8ADgCTAC0AjwAnAeYAFgGOABwB5gAWAY4AHAHmABYBjgAcAeYAFgGOABwB5gAWAY4AHAHmABYBjgAcAeYAFgGOABwB5gAWAY4AHAHmABYBjgAcAeYAFgGOABwB5gAWAY4AHAHmABYBjgAcAdIANgGGADQB0gA2AYYANAHSADYBdQA0AdIANgF1ADQB0gA2AXUANAHSADYBdQA0AdIANgF1ADQBbgAAAVEAAwFuAAABUQADAW4AAAFRAAMBbgAAAVEAAwFo//MBkQAXAZAAAAFYABoBlgAXAUsAGwGWABcBSwAbAa8ABgGRABwBqQAXATcAJACT/+8Aj//tAJMALQFlAB0BIAAgAdwAOwGVADQB5gAWAY4AHAHSADYBdQA0AAD/GwAA/z0AAP9lAAD/lQAA/28CGAAeAhgAIwIYABsCGAAsANgAAAG7ADgCPwAaAm0AGAGpABgCGAAeAhgAEAIYAB4CGAAQAhgAIwIYACACGAAeAhgAGwAAAAEAAQEBAQEADAD4CP8ACAAH//4ACQAI//0ACgAJ//0ACwAK//0ADAAL//0ADQAM//wADgAM//wADwAN//wAEAAO//wAEQAP//sAEgAQ//sAEwAR//sAFAAR//sAFQAS//oAFgAT//oAFwAU//oAGAAV//oAGQAW//kAGgAX//kAGwAX//kAHAAY//kAHQAZ//gAHgAa//gAHwAb//gAIAAc//gAIQAd//cAIgAd//cAIwAe//cAJAAf//cAJQAg//YAJgAh//YAJwAi//YAKAAi//YAKQAj//UAKgAk//UAKwAl//UALAAm//UALQAn//QALgAo//QALwAo//QAMAAp//QAMQAq//MAMgAr//MAMwAs//MANAAt//MANQAu//IANgAu//IANwAv//IAOAAw//IAOQAx//EAOgAy//EAOwAz//EAPAAz//EAPQA0//AAPgA1//AAPwA2//AAQAA3//AAQQA4/+8AQgA5/+8AQwA5/+8ARAA6/+8ARQA7/+4ARgA8/+4ARwA9/+4ASAA+/+4ASQA//+0ASgA//+0ASwBA/+0ATABB/+0ATQBC/+wATgBD/+wATwBE/+wAUABE/+wAUQBF/+sAUgBG/+sAUwBH/+sAVABI/+sAVQBJ/+oAVgBK/+oAVwBK/+oAWABL/+oAWQBM/+kAWgBN/+kAWwBO/+kAXABP/+kAXQBQ/+gAXgBQ/+gAXwBR/+gAYABS/+gAYQBT/+cAYgBU/+cAYwBV/+cAZABV/+cAZQBW/+YAZgBX/+YAZwBY/+YAaABZ/+YAaQBa/+UAagBb/+UAawBb/+UAbABc/+UAbQBd/+QAbgBe/+QAbwBf/+QAcABg/+QAcQBh/+MAcgBh/+MAcwBi/+MAdABj/+MAdQBk/+IAdgBl/+IAdwBm/+IAeABm/+IAeQBn/+EAegBo/+EAewBp/+EAfABq/+EAfQBr/+AAfgBs/+AAfwBs/+AAgABt/+AAgQBu/98AggBv/98AgwBw/98AhABx/98AhQBy/94AhgBy/94AhwBz/94AiAB0/94AiQB1/90AigB2/90AiwB3/90AjAB3/90AjQB4/9wAjgB5/9wAjwB6/9wAkAB7/9wAkQB8/9sAkgB9/9sAkwB9/9sAlAB+/9sAlQB//9oAlgCA/9oAlwCB/9oAmACC/9oAmQCD/9kAmgCD/9kAmwCE/9kAnACF/9kAnQCG/9gAngCH/9gAnwCI/9gAoACI/9gAoQCJ/9cAogCK/9cAowCL/9cApACM/9cApQCN/9YApgCO/9YApwCO/9YAqACP/9YAqQCQ/9UAqgCR/9UAqwCS/9UArACT/9UArQCU/9QArgCU/9QArwCV/9QAsACW/9QAsQCX/9MAsgCY/9MAswCZ/9MAtACZ/9MAtQCa/9IAtgCb/9IAtwCc/9IAuACd/9IAuQCe/9EAugCf/9EAuwCf/9EAvACg/9EAvQCh/9AAvgCi/9AAvwCj/9AAwACk/9AAwQCl/88AwgCl/88AwwCm/88AxACn/88AxQCo/84AxgCp/84AxwCq/84AyACq/84AyQCr/80AygCs/80AywCt/80AzACu/80AzQCv/8wAzgCw/8wAzwCw/8wA0ACx/8wA0QCy/8sA0gCz/8sA0wC0/8sA1AC1/8sA1QC2/8oA1gC2/8oA1wC3/8oA2AC4/8oA2QC5/8kA2gC6/8kA2wC7/8kA3AC7/8kA3QC8/8gA3gC9/8gA3wC+/8gA4AC//8gA4QDA/8cA4gDB/8cA4wDB/8cA5ADC/8cA5QDD/8YA5gDE/8YA5wDF/8YA6ADG/8YA6QDH/8UA6gDH/8UA6wDI/8UA7ADJ/8UA7QDK/8QA7gDL/8QA7wDM/8QA8ADM/8QA8QDN/8MA8gDO/8MA8wDP/8MA9ADQ/8MA9QDR/8IA9gDS/8IA9wDS/8IA+ADT/8IA+QDU/8EA+gDV/8EA+wDW/8EA/ADX/8EA/QDY/8AA/gDY/8AA/wDZ/8AAAAADAAAAAwAABDYAAQAAAAAAHAADAAEAAAHmAAYBygAAACAA4AHwAAIAAwAEAAUABgAHAAgACQAKAAsADAANAA4ADwAQABEAEgATABQAFQAWABcAGAAZABoAGwAcAB0AHgAfACAAIQAiACMAJAAlACYAJwAoACkAKgArACwALQAuAC8AMAAxADIAMwA0ADUANgA3ADgAOQA6ADsAPAA9AD4APwBAAEEAQgBDAEQARQBGAEcASABJAEoASwBMAE0ATgBPAFAAUQBSAFMAVABVAFYAVwBYAFkAWgBbAFwAXQBeAF8AAAFDAAABNQDMATgBPAE5AToAzQE9AMcBQADFAAAAygAAAAABMwE0ATYBNwE7ATEBMgDTAUUAyAFBAMYAAADLAMkAAQBkAGUAZgBnAGgAaQBqAGsAbABtAG4AbwAOAHAAcQByAHMAdAB1AHYAdwB4AHkAegB7AHwAfQB+AH8AgACBAIIAgwCEAIUAhgCHAIgAiQCKAIsAjACNAI4AjwCQAJEAkgCTAJQAlQCWAJcAmACZAJoAmwCcAJ0AngCfAKAAoQCiAKMApAClAKYApwCoAKkAqgCrAKwArQCuAK8AsACxALIAswC0ALUAtgC3ALgAuQC6ALsAvAC9AL4AvwDAMEABAJQAAAAigCAAAYACgAgAH4AjgCeAKAArACtAP8BAwEHAQ0BEQEfASkBMQFCAVMBXwFhAWkBeAF+AZIBoQGwAscC3QMBAwMDCQMjDjoOWx75IA8gFCAaIB4gIiAmIDAgMyA6IEQgoyCsIRMhIiEmIS4hWiFeIgIiBiIPIhIiGiIeIisiSCJgImUlyiXM9xr3HfiC+wL//wAAACAAIQCOAJ4AoAChAK0ArgECAQYBDAEQAR4BKAEwAUEBUgFeAWABaAF4AX0BkgGgAa8CxgLYAwADAwMJAyMOAA4/HqAgDCATIBggHCAgICYgMCAyIDkgRCCjIKshEyEiISYhLiFTIVsiAiIGIg8iESIaIh4iKyJIImAiZCXKJcz3APcb+ID7Af//AAD/4QA8AC0AAP/DAAD/wgDQAM4AygDIALwAtAAA/4L/cwCB/2cAef9R/03/OgBDADb+B/33AAD+5f7e/sfy1fLR4tbhIeEe4RvhGuEZ4RbhDeEM4Qfg/uEtAADgMeAj4CDgGeCi4JHfRt9D3zvfOt8z3zDfJN8I3vHe7tuK24kKVgAACXEGcgABAIoAAAAAAAAAhAAAAIIAAAAAAAAAAAAAAAAAAAB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaAAAAAAAAAfAAAQAOAd4AwgHrAekB0QFDAfQBcQFyAAQCUAAAAIoAgAAYAAoAIAB+AI4AngCgAKwArQD/AQMBBwENAREBHwEpATEBQgFTAV8BYQFpAXgBfgGSAaEBsALHAt0DAQMDAwkDIw46Dlse+SAPIBQgGiAeICIgJiAwIDMgOiBEIKMgrCETISIhJiEuIVohXiICIgYiDyISIhoiHiIrIkgiYCJlJcolzPca9x34gvsC//8AAAAgACEAjgCeAKAAoQCtAK4BAgEGAQwBEAEeASgBMAFBAVIBXgFgAWgBeAF9AZIBoAGvAsYC2AMAAwMDCQMjDgAOPx6gIAwgEyAYIBwgICAmIDAgMiA5IEQgoyCrIRMhIiEmIS4hUyFbIgIiBiIPIhEiGiIeIisiSCJgImQlyiXM9wD3G/iA+wH//wAA/+EAPAAtAAD/wwAA/8IA0ADOAMoAyAC8ALQAAP+C/3MAgf9nAHn/Uf9N/zoAQwA2/gf99wAA/uX+3v7H8tXy0eLW4SHhHuEb4RrhGeEW4Q3hDOEH4P7hLQAA4DHgI+Ag4BngouCR30bfQ9873zrfM98w3yTfCN7x3u7bituJClYAAAlxBnIAAQCKAAAAAAAAAIQAAACCAAAAAAAAAAAAAAAAAAAAdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaAAAAAAAAAfAAAQAOAd4AwgHrAekB0QFDAfQBcQFyAAAuAAALEu4AAlQWLEBAY5ZuAH/hbgARB25AAkAA19eLbgAASwgIEVpRLABYC24AAIsuAABKiEtuAADLCBGsAMlRlJYI1kgiiCKSWSKIEYgaGFksAQlRiBoYWRSWCNlilkvILAAU1hpILAAVF==';
const FONT_BOLD_BASE64 = 'AAEAAAAYAQAABACAR0RFRgQiB0AAAXOIAAAANEdQT1OM1rlcAAFzvAAAF0ZHU1VC+npHzgABiwQAABqmTFRTSEA59scAAApcAAACAU9TLzKlWlR9AAACCAAAAGBQQ0xUhJ9GzQABc1AAAAA2VkRNWGiFb+oAAAxgAAAF4GNtYXCnLjp3AABASAAABoZjdnQgABQAAAAASEgAAAACZmVhdAAGBFcAAaWsAAAALGZwZ20GWZw3AABG0AAAAXNnYXNwABcACQABc0AAAAAQZ2x5ZoBj9bQAAEhMAADWFGhkbXhIFrcjAAASQAAALghoZWFkNDBw0AAAAYwAAAA2aGhlYQVUBCoAAAHEAAAAJGhtdHjEmvsNAAACaAAAB/RrZXJndtnCrAABIlwAACE8bG9jYTuncdIAAR5gAAAD/G1heHAEOgQ6AAAB6AAAACBtb3J4A9e4DQABpdgAACYYbmFtZXNyEM4AAUOYAAAiqHBvc3Th7BqnAAFmQAAADP9wcmVwdAAAKwAASEQAAAAEAAEAAAABAABv2UP6Xw889QAZA+gAAAAAwTiFPAAAAADBOKkr/i7+NwOzA0wAAQAJAAIAAAAAAAAAAQAAA1L/BgAeA8z+Lv9aA7MAAQAAAAAAAAAAAAAAAAAAAf0AAQAAAf0B0gApAFEABgABAAAAAAAKAAACAAIVAAMAAQADAYwCvAAFAAACvAKKAAAAjAK8AooAAAHdAB4A+ggFAgsFAAQCAAIAA6EAAG9QACBaAAAAAAAAAABwc2sgACAAIPsCA1L/BgA8A1IA+mABAYOAAAAAAVQB3AAAACAADQK6ADUA3AAAAKgAJAEjADEBzgAhAW8AKwKwACcB5gAjAKkAMQD0ACwA9AALAVcAJwGhAB0ArAAZAOIADQCsACYBFP/iAXoAHAF6AEYBegAYAXoAGgF6ABwBegAaAXoAJAF6ABwBegAfAXoAJACsACYArAAZAaEAJAGhAC4BoQAkASEAGAI8AB4Bw///AYwAMgGwABoBywAyAWYAMgFmADIBxgAaAdgAMgCjADIBGv/6AZsAMgFnADICPgAdAdgAMgIGABoBhgAyAgYAGgGLADIBbQATAaUABAHiADIBpv//AmT//AGq//8BjP/6AcMAGwDqAC4BDP/qAOoAHgGiACABeAAAANIAIgFvABoBswAyAVsAGgGzABoBhwAaAP4AEQFMACABpwAyAKMAIACr/9ABVAAyANUAMgJ8ACoBpwAqAZwAGgGvAC4BrwAaAPYAJgEoABoBAgAJAiIAMgFm//wB4P/8AV3/9QFp//wBZgAUAP8AHgCxADwA/wAlAaYAFgFQ/roAAAAAANgAAAAA/t8AqAAkAeAAPQHgAFkB4AAyAeAAOAChADgBfAA2AVUANQIcABsA/AAaAWQAHgHAACICHAAbAXgAAAEVADEBuAAkAQQAGwEEACQBAwA1AZ4ALwF8ADAArAAmAPkANQEEADYBJgATAWQAHgIeABcCHgAXAh4AHwEhABgBw///AcP//wHD//8Bw///AcP//wHD//8CR//2AbAAGgFmADIBZgAyAWYAMgFmADIAowAPAKMADwCj//QAo//dAcsACQHYADICBgAaAgYAGgIGABoCBgAaAgYAGgGhABsCBgAaAeIAMgHiADIB4gAyAeIAMgGM//oBigA1AakALgFvABoBbwAaAW8AGgFvABoBbwAaAW8AGgJtABoBWwAaAYcAGgGHABoBhwAaAYcAGgCjAA8AowAPAKP/9ACj/90BegAkAacAKgGcABoBnAAaAZwAGgGcABoBnAAaAaEAGgGcABoBogAyAaIAMgGiADIBogAyAWn//AG2ADcBaf/8AKMAMgFnABUA2QAIAtMAGgKxABoBbQATASgAGgGM//oBwwAbAWYAFAGU/+UA2gAOATQAOwFWADUAwQA1AQoANQD/ADUBAwAcAWcANQAAAAABhwAeAZ8AFAGvABQBkwAfAZMAHwHFABgBPgATAYYAEwGVABkBnwAUAa8AFAI1AB4CNQAeAakACAGpAAgBdP/yAewAFAInAB8CQAAeAZUAHwGVAB8BhwAeAbYACgFmABkBsQAKAb0ACgG9AAoBngAoAZ4AKAHiAAoB4gAKAakACAGhABUBggAjAUkAFgGHAB4BjwAXAakACAF7ABcBkwAfAc0ACgGPABcBtgAKAdQACgGKABcBgQAhAXwAGAFUAB0AAP8CAVAAEAFQ/0wAAP6NAAD+jQAA/o0AAP6NAAD/UQAA/tkAAP+VAYUAQADQADABiwAwAPz/3wEN/94A/P/cANH/kQG1AEgAAP66AAD/kQAA/ygAAP7ZAAD/ZAAA/00AAP9MAAD/JQHCADgByAAzAcgALwHIAAsByAAaAcgAEwHIABMByAALAcgADgHIABcByAAYAg0AGAK5AE0AAP/vAAD/ygAA/+8AAP9bAU8ACQK1AAkA/QBIAP0AVQD9AFUBgABIAYAAVQGAAFUBfAAnAXwAJwDiAB0B+AAmA8wAJwCDABIA3AASAOoAHgDqAB4Ak//KAgYAHQD+AAoCYAAVAdwAIAFdACYBXQAiAeAAAwHtADUBoQAZAaEAPwGDABgCeAAvAPj/yQGhACYBoQAtAaEAHwGhAB8BlQAcAZYAFAF0ACIAAP4uAAD+LgAA/i4AAP4uAAD/FwAA/rYAAP51AAD+xAAA/twAAP+PAAD/BQAA/rEAAP9ZAAD/PgI1AB4AAP6aAAD+ugAA/m0AAP8yAAD+yQAA/noAAP8FAAD+7gAA/1EAAP7ZAAD/jQGpAAgB2wAKAZUAEQHHABEDugA6AcP//wFvABoBw///AW8AGgHD//8BbwAaAcP//wFvABoBw///AW8AGgHD//8BbwAaAcP//wFvABoBw///AW8AGgHD//8BbwAaAcP//wFvABoBw///AW8AGgHD//8BbwAaAWYAMgGHABoBZgAyAYcAGgFmADIBhwAaAWYAMgGHABoBZgAyAYcAGgFmADIBhwAaAWYAMgGHABoBZgAyAYcAGgCjAA4AowAPAKMAJACjACACBgAaAZwAGgIGABoBnAAaAgYAGgGwACQCBgAaAbAAJAIGABoBsAAkAgYAGgGwACQCBgAaAZwAGgIGABoBsAAaAgYAGgGwABoCBgAaAbAAGgIGABoBsAAaAgYAGgGwABoB4gAyAaIAMgHiADIBogAyAeIAMgGeAC8B4gAyAZ4ALwHiADIBngAvAeIAMgGeAC8B4gAyAZ4ALwGM//oBaf/8AYz/+gFp//wBjP/6AWn//AGM//oBaf/8AYkABgGzABoBw///AW8AGgGwABoBWwAaAbAAGgFbABoBywAJAbMAGgHGABoBTAAgAKP/7gCj/+0AowAnAW0AEwEoABoB4gAyAaIAMgIGABoBnAAaAeIAMgGeAC8AAP9GAAD/GgAA/zEAyAA1AAD/RwIeABcCHgAfAh4AFAIeABwA4gAAAcEAOAJWAB4CdQAIAakACAIeABcCHgAIAh4AFwIeAAgCHgAfAh4AGAIeABcCHgAUAAAB/QEBAQEBATsBAQEBAQEBAQEBAQEBAQEBAQE3AQEBAQEBAQEBAQEBAQEBAQEBAQEBATsBOzcBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBOwEBAQEBAQEBAQEBAQEBAUwBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE7AQEBAQFMAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBOwEBAQEBAS8BAQEBAQEBAQEBAQEBAQEBAQEBAQFMAQFMTAEBAQEBAUxMATM7AUxMTEwBOy9MTExMTExMMwEBAQEBMwFMRAE7AQFEAQEBAUwBAQEBAQEBAQEFEAQEBAQEBAQEBAQEBAQEBREw3AQEBRAEBOwEBAQEBAQEBAQEBAQEBAQEBJgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAUwBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE7OzkBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAAAABAAAIAJCAYCAgMEAwcEAgICAgMEAgICAAMDAwMDAwMDAwICAQQEAgIFBAQEBAMDBAQBAwQDBQQGBAYFAwQEBAYEBAQCAgIEAwIDBAMEBAIDBAECAwIGBAUEBAIDAgQDBAMDAwICAgQEAAIAAgQEBAQBAwMFAgMEBQMDBAICAgQDAgICAwMFBQUDBAQEBAQEBQQDAwMDAQEBAQQEBQUFBQUEBgQEBAQEBQQDAwMDAwMGAwQEBAQBAQEBAwQEBAQEBAQFBAQEBAMFAwEDAgcGAwMEBAMEAgMDAgICAgMABQQEBQUEAwQEBAQGBgQFBAQGBgUFBAUEBQUFBQUFBQUEAwMEBAUDBQUEBQQEBAMDAAMEAAAAAAAAAAQCBAICAgIEAAAAAAAAAAAEBAUFBQQEBAUEBAYGAAAAAAMGAgICAwMDAwMCBQoBAgICAQUCBQQDAwQEBAQDBgIEBAQEBAQDAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAEBAQECQQDBAMEAwQDBAMEAwQDBAMEAwQDBAMEAwMEAwQDBAMEAwQDBAMEAwQBAQEBBQQFBAUEBQQFBAUEBQQFBAUEBQQFBAUEBAQEBAQEBAQEBAQEBAQEAwQDBAMEAwQEBAMEAwQDBAQEAwEBAQMDBAQGBQQEAAAAAgAFBQUFAgQFBgQFBQUFBQUFBQAKCwcCAgMFBAgFAgICAwQCAgIDBAQEBAQEBAQFBAICBAQEAwYFBAQFBAQFBQIDBAQGBQYEBgUEBAUEBgQEBQIDAgQEAgQEAwQEAwMEAgIDAgYEBQQEAgMDBAQFAwQEAwIDBAQAAgACBQUFBQIEAwUDBAQFBAMEAwMDBAQCAgMDBAUFBQMFBQUFBQUGBAQEBAQCAgICBQUFBQUFBQQGBQUFBQQFBAQEBAQEBAYDBAQEBAICAgIEBAQEBAQEBAUEBAQEBAUEAgQCBwcEAwQFBAQCAwMCAwMDBAAFBAQFBQUDBAQEBAcHBAUEBQYHBQUEBQQFBQUFBQYGBQQEAwQEBQQFBQQFBQQFBAMAAwQAAAAAAAAABAIEAwMDAAgQAAAAAAAAAAAUFBQYGBQUFBgUFBgcAAAAAAwcDAwMEBAQEBAIFCwECAgIBBQMGBQMDBQUEBAQGAgQEBAQEBAQAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAQFBAUKBQQFBAUEBQQFBAUEBQQFBAUEBQQFBAUEBAQEBAQEBAQEBAQEBAQEBAICAgIFBAUEBQQFBAUEBQQFBAUEBQQFBAUEBQQFBAUEBQQFBAUEBQQFBAQEBAQEBAQEBAQFBAQDBAMFBAUDAgICBAMFBAYFBQQAAAACAAUFBQUCBAYGBAUFBQUFBQUFAAsLCAICAwUECAUCAwMEBQICAgMEBAQEBAQEBAUEAgIFBQUDBgUEBQUEBAUFAgMFBAYFBwQHBQQFBQUHBQQFAwMDBQQCBAUEBQQDBAUCAgQCBwUGBQUDAwMFBAUEBAQDAgMFBAACAAIFBQUFAgQEBgMEBQYEAwUDAwMFBAIDAwMEBgYGAwUFBQUFBQYFBAQEBAICAgIFBQYGBgYGBQcFBQUFBAUFBAQEBAQEBwQEBAQEAgICAgQFBQUFBQUFBgUFBQUEBgQCBAoFBQUFAwUEBwYEBQUFBgcFBQUFBQUEBQUEBAQEBAQEBAYEBAQEBAQEBAQFBAQEBAQFBAYDBAQEBAICAwMEBQUFBQUFBQYFBQUFBQUFBAQEBAUDAwMCAwUFBQUFAwMFBAUEBQQDBQMABAMEAAAAAAAAAAIEBAUFBAMCAAAAAAAAAAAFBQUGBgUFBQUGBQUHBwAAAAADBwMDAwQEBAQEAgULAQICAgEFAwYFAwMGBQUFBgcCBAQEBAQEBAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAABQUEBQoFBAUFBQUEBQQFBAUEBQQFBAUEBQQFBAUEBAQEBAQEBAQEBAQEBAQEBAICAgIFBAUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEBAQEBAQEBAQEBAQEBAQEBAQEBAUFBQMDBAUEBQYFBQQAAAACAAUFBQUCBAYGBQUFBQUFBQUFAAsLCAICAwUECAUCAwMEBQICAgMEBAQEBAQEBAUEAgIFBQUDBgUEBQUEBAUFAgMFBAYFBwQHBQQFBQUHBQQFAwMDBQQCBAUEBQQDBAUCAgQCBwUGBQUDAwMFBAUEBAQDAgMFBAACAAIFBQUFAgQEBgMEBQYEAwUDAwMFBAIDAwMEBgYGAwUFBQUFBQYFBAQEBAICAgIFBQYGBgYGBQcFBQUFBAUFBAQEBAQEBwQEBAQEAgICAgQFBQUFBQUFBgUFBQUEBgQCBAoFBQUFAwUEBwYEBQUFBgcFBQUFBQUEBQUEBAQEBAQEBAYEBAQEBAQEBAQFBAQEBAQFBAYDBAQEBAICAwMEBQUFBQUFBQYFBQUFBQUFBAQEBAUDAwMCAwUFBQUFAwMFBAUEBQQDBQMABAMEAAAAAAAAAAIEBAUFBAMCAAAAAAAAAAAFBQUGBgUFBQUGBQUHBwAAAAADBwMDAwQEBAQEAgULAQICAgEFAwYFAwMGBQUFBgcCBAQEBAQEBAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAABQUEBQoFBAUFBQUEBQQFBAUEBQQFBAUEBQQFBAUEBAQEBAQEBAQEBAQEBAQEBAICAgIFBAUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEBAQEBAQEBAQEBAQEBAQEBAQEBAUFBQMDBAUEBQYFBQQAAAACAAUFBQUCBAYGBQUFBQUFBQUFAAsLCAICAwUECAUCAwMEBQICAgMEBAQEBAQEBAUEAgIFBQUDBgUEBQUEBAUFAgMFBAYFBwQHBQQFBQUHBQQFAwMDBQQCBAUEBQQDBAUCAgQCBwUGBQUDAwMFBAUEBAQDAgMFBAACAAIFBQUFAgQEBgMEBQYEAwUDAwMFBAIDAwMEBgYGAwUFBQUFBQYFBAQEBAICAgIFBQYGBgYGBQcFBQUFBAUFBAQEBAQEBwQEBAQEAgICAgQFBQUFBQUFBgUFBQUEBgQCBAoFBQUFAwUEBwYEBQUFBgcFBQUFBQUEBQUEBAQEBAQEBAYEBAQEBAQEBAQFBAQEBAQFBAYDBAQEBAICAwMEBQUFBQUFBQYFBQUFBQUFBAQEBAUDAwMCAwUFBQUFAwMFBAUEBQQDBQMABAMEAAAAAAAAAAIEBAUFBAMCAAAAAAAAAAAFBQUGBgUFBQUGBQUHBwAAAAADBwMDAwQEBAQEAgULAQICAgEFAwYFAwMGBQUFBgcCBAQEBAQEBAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAABQUEBQoFBAUFBQUEBQQFBAUEBQQFBAUEBQQFBAUEBAQEBAQEBAQEBAQEBAQEBAICAgIFBAUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEBAQEBAQEBAQEBAQEBAQEBAQEBAUFBQMDBAUEBQYFBQQAAAACAAUFBQUCBAYGBQUFBQUFBQUFAAAGAdIAJQANAAIAAQAWABYAAAAHABYAAQADAPkA+wEgAAEAAgDiAOUAAgABAQ0BDwAAAAIAAQEZAQ0AAAABAAMA8ADyAPQAAgABAWAByAAAAAEACAEDAQYBBwEIAQkBEQEWAR0BHgABAAYBAwEGAQcBCIEQAQoBAAEBbgABAAEBZAAAAAYAAQAEAOMA5AD5APsAAQABAQcAAgABAXYBfAAAAAEAAQBgAAIAAQBCAEQAAAABAAIA4wDkAAIAAQFuAXAAAAABAAEBAQABAAUBCQEKAQsBDAEQAAEAAQFyAAEAAQEYAAEAAQAxAAEABgAiAEIAhACkAdIB0wABAAQAJgBGAIwArAABAAIAKgBKAAEABgAMAFAAlgC2AeMB5AABAAQANgBWAeUB5gAAAgHYACMBDAENAQ4BTAF9AXIBTgFWAWEBXAFYAVkBWgFrAWwBbQFhAWIBYwFkAWUBeABmAWoBawFsAW0BbgFbAVwBXQFeAV8AAgG6AAgAQgBDAEQBGQEaARsBHAEdAAEATAAJAAIAAgASABYAAAAXABYABQABAAEARwABAAEAOgBaAAEAIAAiACQAJgAqAC8AMAA2ADoAQgBEAEYASgBPAFAAVgBaAAEAIAAkACYAKgAvADAANgA6AEIARABGAEoATwBQAFYAWgABAAwAhACMAJYApACsALYB0gHTAeMB5AHlAeYAAgAHAEIARAAAAOIA5QADAQEBAQAHAQYBBgAIAQgBDwAJARgBHwARAVsBZAAZAAIAAgENAQ8AAAFgAWQAAwAAAAEAAAACAAAAAAAAAAAAAQAAACQAAAEAAAEAAQAAACgAAAEEAAABAQACAQQAAgAAAAAAAQAAAA8AACYQAAAACQAAAAgAGwAAAAAAAf////8AGwABAAAAAP////4AAQACAAAAAv////8AAQADAAAAAP////0AGwACAAAABP////8AGwADAAAAAP////sAFwAAAAAAAP////cAFz6AAAAACP////8AAAABAAAAAAAAAAAAAAs0IAAAAgAAAAEAAAAZAAAAHAAAA7YAAAc6AAAJiAAACggAAAqoAAgAIgHKAAQAAQAKAAEACwABAAEAAQAMAAEAAQABAAEADQAOAAEAAQABAAEAAQAPAAEAAQABABAAAQABAAEAAQABAAEAAQARAAEAEgABABMAAQABAAEAFAABAAEAAQABABUAFgABAAEAAQABAAEAFwABAAEAAQAYAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAUABgAHAAgACQAAAAAAAAAAAAIAAAAAAAAAAAAAAAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARAAAAAAAAAAAAAgAAAAAAAAAAAAAAAwAEAAUABgAHAAgACQAKAAsADAANAA4ADwAQABEAAQABABIAAQABABMAFAAVABYAFwABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAGAABAAEAAQABABkAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAaAAEAAQAbABwAHQAeAB8AAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABACAAAQABACEAIgAjACQAJQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAJgABAAEAAQAnAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAoAAEAAQApACoAKwAsAC0AAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAC4AAQABAC8AMAAxADIAMwABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEANAABAAEANQA2ADcAOAA5AAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQA6AAEAAQA7ADwAPQA+AD8AAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAEAAAQABAAEAAQBBAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAQgABAAEAQwBEAEUARgBHAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQBIAAEAAQBJAEoASwBMAE0AAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAE4AAQABAAEATwABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAUAABAAEAUQBSAFMAVABVAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQBWAAEAAQBXAFgAWQBaAFsAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAFwAAQABAF0AXgBfAGAAYQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAAAAAAAAAAQAAAAAACgAAAAAADgAAAAAAEgAAAAAAFgAAAAAAGgAAAAAAHgAAAAAAIgAAAAAAJgAAAAAAKgAAAAAALgAAAAAAMgAAAAAANgAAAAAAOgAAAAAAPgAAAAAAQgAAAAAARgAAAAAACAAAAAAAAoAAAAAAAoAAAAAAAoAAAAAAAoAAAAAAAoAAAAAADAAAAAAAAoAAAAgAEAAAAAAAAoAAABAAAoAAABAAAoAAABAAAoAAABAAAoAAABAAFAAAAAAAAoAAABgAAoAAABgAAoAAABgAAoAAABgAAoAAABgAGAAAAAAAAoAAACAAHAAAAAAAAoAAACgAAoAAACgAAoAAACgAAoAAACgAAoAAACgAIAAAAAAAAoAAADAAAoAAADAAAoAAADAAAoAAADAAAoAAADAAJAAAAAAAAoAAADgAAoAAADgAAoAAADgAAoAAADgAAoAAADgAKAAAAAAAAoAAAEAAAoAAAEAAAoAAAEAAAoAAAEAAAoAAAEAALAAAAAAAAoAAAEgAMAAAAAAAAoAAAFAAAoAAAFAAAoAAAFAAAoAAAFAAAoAAAFAANAAAAAAAAoAAAFgAAoAAAFgAAoAAAFgAAoAAAFgAAoAAAFgAOAAAAAAAAoAAAGAAPAAAAAAAAoAAAGgAAoAAAGgAAoAAAGgAAoAAAGgAQAAAAAAAAoAAAHAAAoAAAHAAAoAAAHAACoAAAHAAAoAAAHAARAAAAAAAAoAAAHgAAoAAAHgAAoAAAHgAAoAAAHgACoAAAHgAAP//+Gb///4z///h2///4z///iG////nP//+J7///+k///4sv///5j///i+////rP//+Nb///+s///47v///7T///kG////rP//+Rb///+s///5Jv///7z///k+////xP//+VL///+4///5Xv///8z///l2////zP//+Y7////UAAAABAAIAAwAEAAAAAAAFAAAAAQACAAMABAAGAAAAAQACAAMABAALAAAAEAAAAAEAAgADAAQAEQAAAAEAAgADAAQAFgAAAAEAAgADAAQAGwAAAAEAAgADAAQAIAAAACUAAAABAAIAAwAEACYAAAABAAIAAwAEACsAAAAwAAAAAQACAAMABAAxAAAAAQACAAMABAA2AAAAAQACAAMABAA7AXgAhQCDAXYAggHUAZABkgCLAY4AigGeAdwAjwGgAI4AkwGkAJcAlQGiAJQBvAHhAJwBugCbAcwBzgCfAcoByAF5AKUAowF3AKIB1QGRAZMAqwGPAKoBnwHdAK8BoQCuALMBpQC3ALUBowC0Ab0B4gC8AbsAuwHNAc8AvwHLAckAAAh4IAAAAgAAAAEAAAAVAAAAHAAAAvIAAAU+AAAHFAAAB3QAAAgEAAgAhAFoAAQAAQABAAEAAQABAAEAAQAJAAEAAQABAAEAAQABAAEAAQABAAoAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAsAAQABAAEAAQABAAEAAQAMAAEAAQABAAEAAQABAAEAAQABAA0AAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEADgAPAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABABAAEgATABQABQAGAAcAEQAIAAAAAAAAAAAAAgAAAAAAAAAAAAMABAAFAAYABwAIAAkACgAAAAsADAANAAAAAAAAAAAAAgAAAAAAAAAAAAMABAAFAAYABwAIAAkACgAAAAsADAANAAEAAQAOAAEAAQAPABAAEQASAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQATAAEAAQAUABUAFgAXAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAYAAEAAQAZABoAGwAcAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAdAAEAAQAeAB8AIAAhAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAiAAEAAQAjACQAJQAmAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAnAAEAAQAoACkAKgArAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAsAAEAAQAtAC4ALwAwAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAxAAEAAQAyADMANAA1AAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQA2AAEAAQA3ADgAOQA7AAEAAQABAAEAAQABAAEAAQA6AAEAAQABAAEAAQA8AAEAAQA9AD4APwBBAAEAAQABAAEAAQABAAEAAQBAAAEAAQABAAEAAQAyADMANAA1AAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQA2AAEAAQA3ADgAOQA7AAEAAQABAAEAAQABAAEAAQA6AAEAAQABAAEAAQA8AAEAAQA9AD4APwBBAAEAAQABAAEAAQABAAEAAQBAAAEAAQABAAEAAQBCAAEAAQBDAEQARQBHAAEAAQABAAEAAQABAAEAAQBGAAEAAQABAAEAAQBIAAEAAQBJAEoASwBNAAEAAQABAAEAAQABAAEAAQBMAAEAAQABAAAAAAAAAABAAAAAAAKAAAAAAAOAAAAAAASAAAAAAAWAAAAAAAaAAAAAAAeAAAAAAAiAAAAAAAmAAAAAAAqAAAAAAAuAAAAAAAyAAAAAAA2AAAAAAAIAAAAAAACgAAAAAACgAAAAAACgAAAAAACgAAAAAAMAAAAAAACgAAACAACgAAACAACgAAACAACgAAACAAQAAAAAAACgAAAEAACgAAAEAACgAAAEAACgAAAEAAUAAAAAAACgAAAGAACgAAAGAACgAAAGAACgAAAGAAYAAAAAAACgAAAIAACgAAAIAACgAAAIAACgAAAIAAcAAAAAAACgAAAKAACgAAAKAACgAAAKAACgAAAKAAgAAAAAAACgAAAMAACgAAAMAACgAAAMAACgAAAMAAkAAAAAAACgAAAOAACgAAAOAACgAAAOAACgAAAOAAoAAAAAAACgAAAQAACgAAAQAACgAAAQAACgAAAQAACgAAAQAAsAAAAAAACgAAASAACgAAASAACgAAASAACgAAASAACgAAASAAwAAAAAAACgAAAUAACgAAAUAACgAAAUAACgAAAUAACgAAAUAA0AAAAAAACgAAAWAACgAAAWAACgAAAWAACgAAAWAACgAAAWAAA///4Zv///gT///h+///9/P//+Jb///3s///4rv///cz///jG///9xP//+N7///20///49v//+Vz///kO///5cP//+Sb///lI///5Pv//+Vz///lW///5cP//+W7///mEAAAABAAIAAAADAAAAAAABAAIAAAADAAQAAAABAAIAAAADAAgAAAABAAIAAAADAAwAAAABAAIAAAADABAAAAABAAIAAAADABQAAAABAAIAAAADABgAAAABAAIAAAADABwAAAABAAIAAwAEACAAAAABAAIAAwAEACUAAAABAAIAAwAEACoAAAABAAIAAwAEAC8BfgGAAXoBfAGYAZoBlAGWAaoBrAGmAagBfwGBAXsBfQGZAZsBlQGXAasBrQGnAakBiAGKAYQBhgGJAYsBhQGHAbQBtgGwAbgBsgG1AbcBsQG5AbMBwgHEAb4BxgHAAcMBxQG/AccBwQAAA+wAAAACAAAAAgAAAA0AAAAcAAACXgAAAvoAAANgAAADgAAAA9IACAADAR4ADAABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAQAAQABAAUAAQABAAYAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEABwABAAoAAQABAAEAAQABAAEAAQABAAEAAQABAAgAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAkAAQABAAEAAQABAAEAAQABAAEACwAAAAAAAAAAAAIAAAAAAAMAAAAAAAQABQAAAAAAAAAAAAAAAgAAAAAAAwAAAAAABAAFAAAAAQABAAYAAQABAAcACAABAAEAAQABAAEAAQABAAEACQABAAEAAQABAAEACgALAAEAAQABAAEAAQAMAAEAAQABAAEAAQANAA4AAQABAAEAAQABAA8AAQABAAEAAQABAAEAAQABAAEAEAAAAAAAAAAAQAAAAAACgAAAAAADgAAAAAAEgAAAAAAFgAAAAAACAAAAAAAAoAAAAAAAoAAAAAADAAAAAAAAoAAAAgAAoAAAAgAEAAAAAAAAoAAABAAAoAAABAAFAAAAAAAAoAAABj///7a///+9P//+/r///xw///8Pv///KwAAACS///8IAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAEAAAABgFzAXQB8gHyAfMB8wHxAAAEzAAAAAIAAAAEAAAADgAAABwAAAJ6AAADkgAABCgAAARYAAAEsgAIAAMBLAANAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEABAABAAEABgABAAEABwABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAIAAEACwABAAEAAQABAAEAAQABAAEAAQABAAEACQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEACgABAAEAAQABAAEAAQABAAEAAQAMAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEABQAAAAAAAAAAAAIAAAAAAAAAAwAAAAAABAAFAAAAAAAAAAAAAAACAAAAAAAAAAMAAAAAAAQABQAAAAEAAQAGAAEAAQABAAcACAABAAEAAQABAAEAAQABAAEACQABAAEACgABAAEAAQABAAEAAQABAAEAAQABAAsAAQABAAEAAQABAAEADAANAAEAAQABAAEAAQAOAAEAAQAPAAEAAQABAAEAAQABAAEAAQABAAEAEAABAAEAAQABAAEAAQARABIAAQABAAEAAQABABMAAQABABQAAQABAAEAAQABAAEAAQABAAEAAQAVAAEAAQABAAEAAQABAAEAAQABAAEAFgABAAEAFwABAAEAGAABAAEAAQABAAEAAQABAAEAAAAAAAAAAEAAAAAAA4AAAAAABYAAAAAAB4AAAAAACYAAAAAACAAAAAAAAoAAAAAAAoAAAAAADAAAAAAACgAAAAAABAAAAAAAAKAAAAMAAKAAAAMABQAAAAAABIAAAAAABgAAAAAAAKAAAAYAAKAAAAYABwAAAAAABoAAAAAACAAAAAAAAoAAAAkACQAAAAAACIAAAAA///+2P//+1r///74///7/P//+6L///x4///8RP//++r///y4AAAAnP//+/b///wwAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAQAAAAAAAYBcwF0AfIB8gHzAfMB8QAAAIQgAAAAAAAACAAAAAYAAAAQAAAAQgAAAGYACAEIABYABAABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAUABQAFAAUABQAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAgAAAAEAAwAAAAAAAoAAAAIAAAAAIAMAAAAABIwgAAABAAAACAAAAA4AAAAUAAAAlgAAAo4AAAOwAAgA4gA+AAsABQAFAAwAAQABAAEAAQABAAEAAQABAAEAAQAEAAEABAABAAQAAQABAAEAAQANAAEADQABAAEAAQABAAEABAABAAEAAQABAAYACAAJAAYABgAGAAYABwAHAAcAAQABAAEAAQABAAEAAQABAAYACgAKAAoACgAKAAYABgAAAAEAAAAAAAYADgAAAAAAAQALAAAAFQAVABsAAAABAAAAAAAGAA4AAAAAAAEACwAAABUAFQAbAAAAAQAAAAAABgAOAAIAAQABAAIAAwAVABUAGwAAAAEAAAAAAAYADgACAAIAAQACAAIAFQAVABsAAAABAAAAAAAGAA4ABAAFAAEABAADABUAFQAbAAAAAQAAAAAABgAOAAcABgABAAcACQAVABUAGwAAAAEAAAAAAAYADgAHAAgAAQAHAAwAFQAVABsAAAABAAAAAAAGAA4ACgANAAEACgAJABUAFQAbAAAAAQAAAAAABgAOABAADwAjABAAEgAVABUAGwAAAAEAAAAAAAYADgAQABEAIwAQABAAFQAVABsAAAABAAAAAAAGAA4AFAATACMAFAASABUAFQAbAAAAAQAAAAAABgAOABYAFwABABYAAwAVABUAGwAAAAEAAAAAAAYADgAWABoAAQAWABYAFQAVABsAAAABAAAAAAAGAA4AGQAYAAEAGQADABUAFQAbAAAAAQAAAAAABgAOABkAGQABABkAGQAVABUAGwAAAAEAAAAAAAYADgAeABwAHQAeACEAFQAVABsAAAABAAAAAAAGAA4AHgAfAB0AHgAeABUAFQAbAAAAAQAAAAAABgAOACAAIgAdACAAIQAVABUAGwAAAAD/////AAIAAP////8AAwAA/////wAEgAD//wAAAAMAAAAB//8ABAAA/////wAFAAD/////AAYAAP//AAIABgAA/////wAHgAD//wADAAYAAAAEAAIAAgAA/////wAGAAD//wAFAAcAAP////8ACAAA/////wAIAAD//wAGAAkAAP////8ACQAA//8ABgAKgAD//wAAAAoAAP//AAYACQAAAAH//wALgAD/////AAwAAP////8ADQAAAAf//wANAAD/////AA4AAP////8ADgAAAAf//wAPAAD/////AA8AAP//AAYAAgAA//8ACAAQAAD/////ABAAAP//AAYAEAAAAAH//wARgAD//wAAABEAAP//AAYAAgAA/////wAAAAAAJAAAADQAAAB0AAAARAAAAFQAAABkAAAArgAAAMIAAAC6AAgBGQAFAWABYQFiAWMBZAAIAWAABQEZARoBGwEcAR0ACAEZAAUBWwFcAV0BXgFfAAgBWwAFAWkBagFrAWwBbQAIARkABQFpAWoBawFsAW0ACAEGABoBZgAAAGABVwFYAVkBWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaAFpAWoBawFsAW0BZwBjAAgBDQADAW4BbwFwAAgBBwABARYACADiAAQBZQAAAAABVgAAAZggAAABAAAACAAAAAYAAAAUAAABNgAAAVoAAAF8AAgA4wCOAAQABAABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAFAAUABQAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAIAAAABAAMAAAAA/////wACgAD/////AAIAAP////8AAAAAAAD//wAAAAAABAAIAOMAAgH0AXEAAAAAAoggAAABAAAACAAAAAYAAAAUAAACLAAAAlAAAAJwAAgAYAEJAAUAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAEAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAFAAUABQAFAAEAAQABAAEAAQABAAEAAQABAAEABQAFAAUAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAIAAAABAAMAAAAA/////wACgAD/////AAIAAP////8AAAAAAAD//wAAAAQACAEBAAEBcg==';

const FreeEducation = () => {
  const [semester, setSemester] = useState('1');
  const [academicYear, setAcademicYear] = useState('');
  const [selectedClass, setSelectedClass] = useState('ทั้งหมด');
  const [selectedRoom, setSelectedRoom] = useState('ทั้งหมด');
  const [meetingDate, setMeetingDate] = useState('.......... พฤษภาคม ๒๕๖๙');
  const [schoolName, setSchoolName] = useState('โรงเรียนบ้านควนโคกยา');
  const [directorName, setDirectorName] = useState('');
  const [payerName, setPayerName] = useState('');
  const [paymentType, setPaymentType] = useState<'all' | 'uniform' | 'materials'>('all');
  const [payers, setPayers] = useState<Record<string, string>>(() => {
    const saved = localStorage.getItem('free_education_payers');
    return saved ? JSON.parse(saved) : {};
  });
  const [activeView, setActiveView] = useState<'registration' | 'payment'>('registration');
  const [students, setStudents] = useState<Student[]>([]);
  const [loading, setLoading] = useState(false);

  const [amounts, setAmounts] = useState(() => {
    const saved = localStorage.getItem('free_education_amounts');
    return saved ? JSON.parse(saved) : {
      preschool: { uniform: 300, materials: 145 },
      primary: { uniform: 360, materials: 195 }
    };
  });

  const saveAmounts = () => {
    localStorage.setItem('free_education_amounts', JSON.stringify(amounts));
    localStorage.setItem('free_education_payers', JSON.stringify(payers));
    alert('บันทึกการตั้งค่าจำนวนเงินและรายชื่อผู้จ่ายเงินเรียบร้อยแล้ว');
  };

  useEffect(() => {
    if (selectedClass !== 'ทั้งหมด') {
      setPayerName(payers[selectedClass] || '');
    } else {
      setPayerName('');
    }
  }, [selectedClass, payers]);

  const handlePayerChange = (name: string) => {
    setPayerName(name);
    if (selectedClass !== 'ทั้งหมด') {
      setPayers(prev => ({ ...prev, [selectedClass]: name }));
    }
  };

  useEffect(() => {
    async function fetchSettings() {
      const { data } = await supabase.from('settings').select('school_name, current_academic_year, director_name').single();
      if (data?.school_name) setSchoolName(data.school_name);
      if (data?.current_academic_year) setAcademicYear(data.current_academic_year);
      if (data?.director_name) setDirectorName(data.director_name);
    }
    fetchSettings();
  }, []);

  useEffect(() => {
    if (academicYear) {
      fetchStudents();
    }
  }, [academicYear, selectedClass, selectedRoom]);

  const fetchStudents = async () => {
    if (!academicYear) return;
    setLoading(true);
    try {
      let query = supabase
        .from('students')
        .select('*')
        .eq('academic_year', academicYear.toString())
        .order('class_level', { ascending: true })
        .order('room', { ascending: true })
        .order('first_name', { ascending: true });

      if (selectedClass !== 'ทั้งหมด') {
        query = query.eq('class_level', selectedClass);
      }
      
      if (selectedRoom !== 'ทั้งหมด') {
        query = query.eq('room', selectedRoom);
      }

      const { data, error } = await query;
      if (error) throw error;
      
      const filteredData = (data || []).filter(s => 
        !s.graduation_status || 
        s.graduation_status.includes('กำลังศึกษา') || 
        s.graduation_status === 'ปกติ'
      );

      const mappedData = filteredData.map(s => ({
        ...s,
        parent_phone: s.phone_number || s.parent_phone || ''
      }));

      const uniqueData = Array.from(new Map(mappedData.map(s => [s.student_id || s.id, s])).values());
      setStudents(uniqueData as Student[]);
    } catch (err) {
      console.error('Error fetching students:', err);
    } finally {
      setLoading(false);
    }
  };

  const toThaiDigits = (num: string | number) => {
    if (!num) return '';
    const thaiDigits = ['๐', '๑', '๒', '๓', '๔', '๕', '๖', '๗', '๘', '๙'];
    return num.toString().split('').map(d => isNaN(parseInt(d)) ? d : thaiDigits[parseInt(d)]).join('');
  };

  const formatClassThai = (classLevel: string, room: string) => {
    if (!classLevel) return '';
    const match = classLevel.match(/([ก-ฮ]\.)(\d+)/);
    if (match) {
      return `${match[1]}${toThaiDigits(match[2])}/${toThaiDigits(room || '1')}`;
    }
    return `${toThaiDigits(classLevel)}/${toThaiDigits(room || '1')}`;
  };

  const getStudentAmounts = (classLevel: string) => {
    if (!classLevel) return { uniform: 0, materials: 0, total: 0 };
    if (classLevel.startsWith('อ')) {
      return {
        uniform: amounts.preschool.uniform,
        materials: amounts.preschool.materials,
        total: amounts.preschool.uniform + amounts.preschool.materials
      };
    }
    return {
      uniform: amounts.primary.uniform,
      materials: amounts.primary.materials,
      total: amounts.primary.uniform + amounts.primary.materials
    };
  };

  const calculateGrandTotal = () => {
    return students.reduce((sum, s) => {
      const amounts = getStudentAmounts(s.class_level);
      if (paymentType === 'uniform') return sum + amounts.uniform;
      if (paymentType === 'materials') return sum + amounts.materials;
      return sum + amounts.total;
    }, 0);
  };

  const bahttext = (amount: number) => {
    if (isNaN(amount) || amount === 0) return 'ศูนย์บาทถ้วน';
    const thaiNum = ['ศูนย์', 'หนึ่ง', 'สอง', 'สาม', 'สี่', 'ห้า', 'หก', 'เจ็ด', 'แปด', 'เก้า'];
    const thaiUnit = ['', 'สิบ', 'ร้อย', 'พัน', 'หมื่น', 'แสน', 'ล้าน'];
    const convert = (numStr: string) => {
      let subResult = '';
      const n = numStr.length;
      for (let i = 0; i < n; i++) {
        const d = parseInt(numStr[i]);
        const pos = n - 1 - i;
        if (d !== 0) {
          if (pos % 6 === 1 && d === 1) subResult += '';
          else if (pos % 6 === 1 && d === 2) subResult += 'ยี่';
          else if (pos % 6 === 0 && d === 1 && i > 0 && n > 1) subResult += 'เอ็ด';
          else subResult += thaiNum[d];
          subResult += thaiUnit[pos % 6];
        }
        if (pos !== 0 && pos % 6 === 0) subResult += 'ล้าน';
      }
      return subResult;
    };
    let [integer] = amount.toFixed(2).split('.');
    let result = convert(integer) + 'บาทถ้วน';
    return result;
  };

  const handlePrint = () => {
    const isPayment = activeView === 'payment';
    const totalAmount = calculateGrandTotal();
    
    let docTitle = isPayment ? 'แบบหลักฐานการจ่ายเงินอุดหนุนค่าเครื่องแบบนักเรียน และอุปกรณ์การเรียน' : 'ใบลงทะเบียนเข้าร่วมประชุมผู้ปกครอง';
    if (isPayment) {
      if (paymentType === 'uniform') docTitle = 'แบบหลักฐานการจ่ายเงินอุดหนุนค่าเครื่องแบบนักเรียน';
      if (paymentType === 'materials') docTitle = 'แบบหลักฐานการจ่ายเงินอุดหนุนค่าอุปกรณ์การเรียน';
    }

    const tableRows = students.map((student, i) => {
      const studentAmounts = getStudentAmounts(student.class_level);
      if (!isPayment) {
        return `
          <tr>
            <td style="text-align:center;">${toThaiDigits(i + 1)}</td>
            <td style="text-align:left; white-space:nowrap;">${student.prefix}${student.first_name} ${student.last_name}</td>
            <td style="text-align:center;">${formatClassThai(student.class_level, student.room)}</td>
            <td></td>
            <td></td>
            <td style="text-align:center;">${toThaiDigits(student.parent_phone || '')}</td>
            <td></td>
          </tr>
        `;
      }

      let amountCols = '';
      if (paymentType === 'all') {
        amountCols = `
          <td style="text-align:right;">${toThaiDigits(studentAmounts.uniform.toLocaleString())}</td>
          <td style="text-align:right;">${toThaiDigits(studentAmounts.materials.toLocaleString())}</td>
          <td style="text-align:right;">${toThaiDigits(studentAmounts.total.toLocaleString())}</td>
        `;
      } else if (paymentType === 'uniform') {
        amountCols = `<td style="text-align:right;">${toThaiDigits(studentAmounts.uniform.toLocaleString())}</td>`;
      } else {
        amountCols = `<td style="text-align:right;">${toThaiDigits(studentAmounts.materials.toLocaleString())}</td>`;
      }

      return `
        <tr>
          <td style="text-align:center;">${toThaiDigits(i + 1)}</td>
          <td style="text-align:left; white-space:nowrap;">${student.prefix}${student.first_name} ${student.last_name}</td>
          <td style="text-align:center;">${formatClassThai(student.class_level, student.room)}</td>
          ${amountCols}
          <td style="text-align:center;"></td>
          <td></td>
          <td></td>
        </tr>
      `;
    }).join('');

    const headerRow = !isPayment ? `
      <tr>
        <th style="width: 25px;">ที่</th>
        <th style="width: 160px;">ชื่อ - สกุล นักเรียน</th>
        <th style="width: 50px;">ชั้น</th>
        <th style="width: 240px;">ชื่อ - สกุล ผู้ปกครอง</th>
        <th style="width: 65px;">ความสัมพันธ์</th>
        <th style="width: 120px;">เบอร์โทรศัพท์</th>
        <th style="width: 100px;">ลายมือชื่อ</th>
      </tr>
    ` : `
      <tr>
        <th ${paymentType === 'all' ? 'rowspan="2"' : ''} style="width: 25px;">ที่</th>
        <th ${paymentType === 'all' ? 'rowspan="2"' : ''} style="width: 210px;">ชื่อ - สกุล นักเรียน</th>
        <th ${paymentType === 'all' ? 'rowspan="2"' : ''} style="width: 50px;">ชั้น</th>
        <th ${paymentType === 'all' ? 'colspan="2"' : ''}>รายการที่ได้รับเงิน (บาท)</th>
        ${paymentType === 'all' ? '<th rowspan="2" style="width: 70px;">รวมเงิน<br/>(บาท)</th>' : ''}
        <th ${paymentType === 'all' ? 'rowspan="2"' : ''} style="width: 120px;">วัน/เดือน/ปี<br/>ที่รับเงิน</th>
        <th ${paymentType === 'all' ? 'rowspan="2"' : ''} style="width: 180px;">ลายมือชื่อผู้รับเงิน<br/>(ผู้ปกครอง)</th>
        <th ${paymentType === 'all' ? 'rowspan="2"' : ''} style="width: 50px;">หมายเหตุ</th>
      </tr>
      ${paymentType === 'all' ? `
        <tr>
          <th style="width: 60px;">เครื่องแบบ</th>
          <th style="width: 60px;">อุปกรณ์</th>
        </tr>
      ` : ''}
    `;

    const footerTotal = isPayment && students.length > 0 ? `
      <tr style="font-weight:bold;">
        <td colspan="${paymentType === 'all' ? 5 : 3}" style="text-align:right; border: 1px solid black;">รวมเป็นเงินทั้งสิ้น</td>
        <td style="text-align:right; border: 1px solid black;">${toThaiDigits(totalAmount.toLocaleString())}</td>
        <td colspan="3" style="text-align:left; border: 1px solid black;">บาท</td>
      </tr>
    ` : '';

    const html = `
      <html>
        <head>
          <title>${docTitle}</title>
          <style>
            @font-face {
              font-family: 'TH Sarabun New';
              src: url(data:font/truetype;charset=utf-8;base64,${FONT_BASE64}) format('truetype');
              font-weight: normal; font-style: normal;
            }
            @font-face {
              font-family: 'TH Sarabun New';
              src: url(data:font/truetype;charset=utf-8;base64,${FONT_BOLD_BASE64}) format('truetype');
              font-weight: bold; font-style: normal;
            }
            @media print {
              @page { size: A4; margin: 15mm 10mm; }
              body { background: white; }
              .no-print-btn { display: none !important; }
            }
            .sarabun { font-family: 'TH Sarabun New', sans-serif; color: black; line-height: 1.0; }
            body { margin: 0; padding: 0; background: #f0f0f0; }
            .page { 
              background: white; width: 210mm; min-height: 297mm; 
              padding: 15mm; margin: 1cm auto; box-sizing: border-box; 
              box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            }
            .header { text-align: center; margin-bottom: 10px; }
            table { width: 100%; border-collapse: collapse; margin-top: 5px; }
            th, td { border: 1px solid black !important; padding: 2px 4px !important; font-size: 15pt; }
            th { background: #f8fafc; font-weight: bold; text-align: center; }
            .footer-area { margin-top: 15px; font-size: 16pt; }
            .sign-table { border: none !important; margin-top: 20px; width: 100%; }
            .sign-table td { border: none !important; padding: 0 !important; }
            .no-print-btn { 
              position: fixed; top: 20px; right: 20px; 
              background: #2563eb; color: white; border: none; 
              padding: 12px 24px; border-radius: 12px; cursor: pointer;
              font-weight: bold; z-index: 9999;
            }
          </style>
        </head>
        <body class="sarabun">
          <button class="no-print-btn" onclick="window.print()">🖨️ คลิกเพื่อสั่งพิมพ์</button>
          <div class="page">
            <div class="header">
              <h1 style="font-size: 18pt; font-weight: bold; margin: 0;">${docTitle}</h1>
              <h2 style="font-size: 16pt; font-weight: normal; margin: 2px 0;">โครงการสนับสนุนค่าใช้จ่ายในการจัดการศึกษาตั้งแต่ระดับอนุบาลจนจบการศึกษาขั้นพื้นฐาน</h2>
              <h2 style="font-size: 16pt; font-weight: normal; margin: 2px 0;">ภาคเรียนที่ ${toThaiDigits(semester)} ปีการศึกษา ${toThaiDigits(academicYear)} ${selectedClass !== 'ทั้งหมด' ? ` (ชั้น ${selectedClass})` : ''}</h2>
              <h2 style="font-size: 16pt; font-weight: normal; margin: 2px 0;">${schoolName}</h2>
            </div>
            <table>
              <thead>${headerRow}</thead>
              <tbody>
                ${tableRows}
                ${footerTotal}
              </tbody>
            </table>
            <div class="footer-area">
              <p style="margin: 5px 0;">รวมเงินตัวอักษร (${bahttext(totalAmount)})</p>
              <table class="sign-table">
                <tr>
                  <td style="width: 50%; text-align: center;">
                    <div style="display: inline-block; text-align: left;">
                      ลงชื่อ ........................................................... ผู้จ่ายเงิน<br/>
                      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;( ${payerName || '...........................................................'} )
                    </div>
                  </td>
                  <td style="width: 50%; text-align: center;">
                    <div style="display: inline-block; text-align: left;">
                      ลงชื่อ ...........................................................<br/>
                      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;( ${directorName || '...........................................................'} )<br/>
                      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ผู้อำนวยการสถานศึกษา
                    </div>
                  </td>
                </tr>
              </table>
            </div>
          </div>
          <script>window.onload = function() { setTimeout(() => { window.print(); }, 800); }</script>
        </body>
      </html>
    `;
    const win = window.open('', '_blank');
    win?.document.write(html);
    win?.document.close();
  };

  const classOptions = [
    'ทั้งหมด', 'อ.1', 'อ.2', 'อ.3', 
    'ป.1', 'ป.2', 'ป.3', 'ป.4', 'ป.5', 'ป.6'
  ];

  return (
    <div className="space-y-6">
      <div className="bg-white p-6 rounded-3xl shadow-sm border border-slate-100 print:hidden">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 items-end">
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-400 uppercase tracking-widest px-1">ภาคเรียน</label>
            <select value={semester} onChange={(e) => setSemester(e.target.value)} className="w-full bg-slate-50 border-none rounded-2xl px-4 py-3 text-sm font-bold focus:ring-2 focus:ring-brand-primary">
              <option value="1">ภาคเรียนที่ ๑</option>
              <option value="2">ภาคเรียนที่ ๒</option>
            </select>
          </div>
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-400 uppercase tracking-widest px-1">ปีการศึกษา</label>
            <input type="number" value={academicYear} onChange={(e) => setAcademicYear(e.target.value)} className="w-full bg-slate-50 border-none rounded-2xl px-4 py-3 text-sm font-bold focus:ring-2 focus:ring-brand-primary" />
          </div>
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-400 uppercase tracking-widest px-1 flex items-center gap-1">
              <FilterIcon size={12} /> ระดับชั้น
            </label>
            <select value={selectedClass} onChange={(e) => setSelectedClass(e.target.value)} className="w-full bg-slate-50 border-none rounded-2xl px-4 py-3 text-sm font-bold focus:ring-2 focus:ring-brand-primary">
              {classOptions.map(opt => <option key={opt} value={opt}>{opt}</option>)}
            </select>
          </div>
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-400 uppercase tracking-widest px-1 flex items-center gap-1">
              <FilterIcon size={12} /> ห้อง
            </label>
            <select value={selectedRoom} onChange={(e) => setSelectedRoom(e.target.value)} className="w-full bg-slate-50 border-none rounded-2xl px-4 py-3 text-sm font-bold focus:ring-2 focus:ring-brand-primary">
              <option value="ทั้งหมด">ทั้งหมด</option>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
            </select>
          </div>
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-400 uppercase tracking-widest px-1">ชื่อผู้จ่ายเงิน</label>
            <input type="text" value={payerName} onChange={(e) => handlePayerChange(e.target.value)} className="w-full bg-slate-50 border-none rounded-2xl px-4 py-3 text-sm font-bold focus:ring-2 focus:ring-brand-primary" placeholder="ชื่อ-สกุล ผู้จ่ายเงิน" />
          </div>
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-400 uppercase tracking-widest px-1">รายการจ่ายเงิน</label>
            <select value={paymentType} onChange={(e) => setPaymentType(e.target.value as any)} className="w-full bg-slate-50 border-none rounded-2xl px-4 py-3 text-sm font-bold focus:ring-2 focus:ring-brand-primary">
              <option value="all">ทั้งหมด (เครื่องแบบ + อุปกรณ์)</option>
              <option value="uniform">เฉพาะค่าเครื่องแบบนักเรียน</option>
              <option value="materials">เฉพาะค่าอุปกรณ์การเรียน</option>
            </select>
          </div>
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-400 uppercase tracking-widest px-1">วันที่ประชุม/จ่ายเงิน</label>
            <input type="text" value={meetingDate} onChange={(e) => setMeetingDate(e.target.value)} className="w-full bg-slate-50 border-none rounded-2xl px-4 py-3 text-sm font-bold focus:ring-2 focus:ring-brand-primary" placeholder="เช่น .......... พฤษภาคม ๒๕๖๙" />
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-6 p-6 bg-slate-50 rounded-3xl border border-slate-100">
          <div className="space-y-4">
            <h4 className="text-sm font-black text-slate-700 uppercase tracking-widest flex items-center gap-2"><div className="w-2 h-2 bg-blue-500 rounded-full"></div> ระดับปฐมวัย (อนุบาล)</h4>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase">ค่าเครื่องแบบ</label>
                <input type="number" value={amounts.preschool.uniform} onChange={(e) => setAmounts({...amounts, preschool: {...amounts.preschool, uniform: parseInt(e.target.value) || 0}})} className="w-full bg-white border border-slate-200 rounded-xl px-4 py-2 text-sm font-bold" />
              </div>
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase">ค่าอุปกรณ์</label>
                <input type="number" value={amounts.preschool.materials} onChange={(e) => setAmounts({...amounts, preschool: {...amounts.preschool, materials: parseInt(e.target.value) || 0}})} className="w-full bg-white border border-slate-200 rounded-xl px-4 py-2 text-sm font-bold" />
              </div>
            </div>
          </div>
          <div className="space-y-4">
            <h4 className="text-sm font-black text-slate-700 uppercase tracking-widest flex items-center gap-2"><div className="w-2 h-2 bg-green-500 rounded-full"></div> ระดับประถมศึกษา</h4>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase">ค่าเครื่องแบบ</label>
                <input type="number" value={amounts.primary.uniform} onChange={(e) => setAmounts({...amounts, primary: {...amounts.primary, uniform: parseInt(e.target.value) || 0}})} className="w-full bg-white border border-slate-200 rounded-xl px-4 py-2 text-sm font-bold" />
              </div>
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase">ค่าอุปกรณ์</label>
                <input type="number" value={amounts.primary.materials} onChange={(e) => setAmounts({...amounts, primary: {...amounts.primary, materials: parseInt(e.target.value) || 0}})} className="w-full bg-white border border-slate-200 rounded-xl px-4 py-2 text-sm font-bold" />
              </div>
            </div>
          </div>
          <div className="md:col-span-2 flex justify-end">
            <button onClick={saveAmounts} className="bg-brand-primary/10 text-brand-primary hover:bg-brand-primary hover:text-white px-4 py-2 rounded-xl text-xs font-bold transition-all">บันทึกการตั้งค่าจำนวนเงิน</button>
          </div>
        </div>

        <div className="flex flex-wrap gap-4 mt-6 pt-6 border-t border-slate-50">
          <div className="flex gap-2">
            <button onClick={() => setActiveView('registration')} className={`flex items-center gap-2 px-6 py-3 rounded-2xl font-bold text-sm transition-all ${activeView === 'registration' ? 'bg-brand-primary text-white shadow-lg shadow-green-100' : 'bg-slate-50 text-slate-600 hover:bg-slate-100'}`}><UsersIcon size={18} /> ใบลงทะเบียน</button>
            <button onClick={() => setActiveView('payment')} className={`flex items-center gap-2 px-6 py-3 rounded-2xl font-bold text-sm transition-all ${activeView === 'payment' ? 'bg-brand-primary text-white shadow-lg shadow-green-100' : 'bg-slate-50 text-slate-600 hover:bg-slate-100'}`}><CreditCardIcon size={18} /> แบบหลักฐานการจ่ายเงิน</button>
          </div>
          <button onClick={handlePrint} disabled={loading} className="ml-auto flex items-center gap-2 bg-slate-800 text-white px-8 py-3 rounded-2xl font-bold text-sm hover:bg-slate-700 transition-all shadow-lg shadow-slate-200 disabled:opacity-50">
            {loading ? <Loader2Icon className="animate-spin" size={18} /> : <PrinterIcon size={18} />} พิมพ์เอกสาร ({students.length} รายชื่อ)
          </button>
        </div>
      </div>

      <div className="flex justify-center bg-slate-100 p-8 min-h-screen overflow-x-auto print:hidden">
        <div className="bg-white shadow-2xl w-[210mm] min-h-[297mm] p-[15mm] box-border relative text-black" style={{ fontFamily: "'TH Sarabun New', sans-serif" }}>
          <div className="sarabun">
            {activeView === 'registration' ? (
              <>
                <div className="text-center mb-6 leading-tight">
                  <h1 className="text-[20pt] font-bold">ใบลงทะเบียนเข้าร่วมประชุมผู้ปกครอง</h1>
                  <h2 className="text-[17pt]">ภาคเรียนที่ {toThaiDigits(semester)} ปีการศึกษา {toThaiDigits(academicYear)} {selectedClass !== 'ทั้งหมด' && ` (ชั้น ${selectedClass})`}</h2>
                  <h2 className="text-[17pt]">ณ ห้องประชุม{schoolName}</h2>
                  <p className="text-[15pt] mt-2">วันที่ {toThaiDigits(meetingDate)}</p>
                </div>
                <table className="w-full border-collapse border border-black table-auto">
                  <thead>
                    <tr className="bg-slate-50">
                      <th className="border border-black p-1 text-[15pt] w-12 text-center">ที่</th>
                      <th className="border border-black p-1 text-[15pt] w-[180px]">ชื่อ - สกุล นักเรียน</th>
                      <th className="border border-black p-1 text-[15pt] w-16 text-center">ชั้น</th>
                      <th className="border border-black p-1 text-[15pt]">ชื่อ - สกุล ผู้ปกครอง</th>
                      <th className="border border-black p-1 text-[15pt] w-24 text-center">ความสัมพันธ์</th>
                      <th className="border border-black p-1 text-[15pt] w-32 text-center">เบอร์โทรศัพท์</th>
                      <th className="border border-black p-1 text-[15pt] w-28 text-center">ลายมือชื่อ</th>
                    </tr>
                  </thead>
                  <tbody>
                    {students.map((student, i) => (
                      <tr key={student.id}>
                        <td className="border border-black p-1 text-[15pt] text-center">{toThaiDigits(i + 1)}</td>
                        <td className="border border-black p-1 text-[15pt] whitespace-nowrap">{student.prefix}{student.first_name} {student.last_name}</td>
                        <td className="border border-black p-1 text-[15pt] text-center whitespace-nowrap">{formatClassThai(student.class_level, student.room)}</td>
                        <td className="border border-black p-1 text-[15pt]"></td>
                        <td className="border border-black p-1 text-[15pt]"></td>
                        <td className="border border-black p-1 text-[15pt] text-center">{toThaiDigits(student.parent_phone || '')}</td>
                        <td className="border border-black p-1 text-[15pt]"></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </>
            ) : (
              <>
                <div className="text-center mb-6 leading-tight">
                  <h1 className="text-[18pt] font-bold">
                    {paymentType === 'all' ? 'แบบหลักฐานการจ่ายเงินอุดหนุนค่าเครื่องแบบนักเรียน และอุปกรณ์การเรียน' : 
                     paymentType === 'uniform' ? 'แบบหลักฐานการจ่ายเงินอุดหนุนค่าเครื่องแบบนักเรียน' : 
                     'แบบหลักฐานการจ่ายเงินอุดหนุนค่าอุปกรณ์การเรียน'}
                  </h1>
                  <h2 className="text-[16pt]">โครงการสนับสนุนค่าใช้จ่ายในการจัดการศึกษาตั้งแต่ระดับอนุบาลจนจบการศึกษาขั้นพื้นฐาน</h2>
                  <h2 className="text-[16pt]">ภาคเรียนที่ {toThaiDigits(semester)} ปีการศึกษา {toThaiDigits(academicYear)} {selectedClass !== 'ทั้งหมด' && ` (ชั้น ${selectedClass})`}</h2>
                  <h2 className="text-[16pt]">{schoolName}</h2>
                </div>
                <table className="w-full border-collapse border border-black table-auto">
                  <thead>
                    <tr className="bg-slate-50">
                      <th rowSpan={paymentType === 'all' ? 2 : 1} className="border border-black p-1 text-[14pt] w-10 text-center">ที่</th>
                      <th rowSpan={paymentType === 'all' ? 2 : 1} className="border border-black p-1 text-[14pt] w-[180px]">ชื่อ - สกุล นักเรียน</th>
                      <th rowSpan={paymentType === 'all' ? 2 : 1} className="border border-black p-1 text-[14pt] w-16 text-center">ชั้น</th>
                      <th colSpan={paymentType === 'all' ? 2 : 1} className="border border-black p-1 text-[14pt] text-center">รายการที่ได้รับเงิน (บาท)</th>
                      {paymentType === 'all' && <th rowSpan={2} className="border border-black p-1 text-[14pt] w-20 text-center">รวมเงิน<br/>(บาท)</th>}
                      <th rowSpan={paymentType === 'all' ? 2 : 1} className="border border-black p-1 text-[14pt] w-32 text-center">วัน/เดือน/ปี<br/>ที่รับเงิน</th>
                      <th rowSpan={paymentType === 'all' ? 2 : 1} className="border border-black p-1 text-[14pt] w-32 text-center">ลายมือชื่อผู้รับเงิน<br/>(ผู้ปกครอง)</th>
                      <th rowSpan={paymentType === 'all' ? 2 : 1} className="border border-black p-1 text-[14pt] w-16 text-center">หมายเหตุ</th>
                    </tr>
                    {paymentType === 'all' && (
                      <tr className="bg-slate-50">
                        <th className="border border-black p-1 text-[14pt] w-16 text-center">เครื่องแบบ</th>
                        <th className="border border-black p-1 text-[14pt] w-16 text-center">อุปกรณ์</th>
                      </tr>
                    )}
                  </thead>
                  <tbody>
                    {students.map((student, i) => {
                      const studentAmounts = getStudentAmounts(student.class_level);
                      return (
                        <tr key={student.id}>
                          <td className="border border-black p-1 text-[15pt] text-center">{toThaiDigits(i + 1)}</td>
                          <td className="border border-black p-1 text-[15pt] whitespace-nowrap">{student.prefix}{student.first_name} {student.last_name}</td>
                          <td className="border border-black p-1 text-[15pt] text-center whitespace-nowrap">{formatClassThai(student.class_level, student.room)}</td>
                          
                          {paymentType === 'all' ? (
                            <>
                              <td className="border border-black p-1 text-[15pt] text-right">{toThaiDigits(studentAmounts.uniform.toLocaleString())}</td>
                              <td className="border border-black p-1 text-[15pt] text-right">{toThaiDigits(studentAmounts.materials.toLocaleString())}</td>
                              <td className="border border-black p-1 text-[15pt] text-right">{toThaiDigits(studentAmounts.total.toLocaleString())}</td>
                            </>
                          ) : paymentType === 'uniform' ? (
                            <td className="border border-black p-1 text-[15pt] text-right">{toThaiDigits(studentAmounts.uniform.toLocaleString())}</td>
                          ) : (
                            <td className="border border-black p-1 text-[15pt] text-right">{toThaiDigits(studentAmounts.materials.toLocaleString())}</td>
                          )}

                          <td className="border border-black p-1 text-[15pt] text-center"></td>
                          <td className="border border-black p-1 text-[15pt]"></td>
                          <td className="border border-black p-1 text-[15pt]"></td>
                        </tr>
                      );
                    })}
                    {students.length > 0 && (
                      <tr className="font-bold bg-slate-50">
                        <td colSpan={paymentType === 'all' ? 5 : 3} className="border border-black p-1 text-[15pt] text-right">รวมเป็นเงินทั้งสิ้น</td>
                        <td className="border border-black p-1 text-[15pt] text-right">{toThaiDigits(calculateGrandTotal().toLocaleString())}</td>
                        <td colSpan={3} className="border border-black p-1 text-[15pt]">บาท</td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default FreeEducation;
